ALTER TABLE "Destination" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Package" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "FAQ" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Testimonial" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Booking" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Wishlist" DISABLE ROW LEVEL SECURITY;
ALTER TABLE "Hero" DISABLE ROW LEVEL SECURITY;
